import 'package:flutter/material.dart';
import 'package:test_edit_controller/fetch_data.dart';
import 'package:test_edit_controller/transaction_class.dart';

class TransactionHome extends StatefulWidget {
  const TransactionHome({super.key});

  @override
  State<TransactionHome> createState() => _TransactionHomeState();
}

class _TransactionHomeState extends State<TransactionHome> {
  late Future<List<Transaction>> futureTransaction;
  TextEditingController accountIdController = TextEditingController();
  TextEditingController amountController = TextEditingController();

  @override
  void initState() {
    // TODO: implement initState
    super.initState();
    futureTransaction = fetchTransaction();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
        appBar: AppBar(
          title: const Text('Kopo Kopo'),
        ),
        body: SingleChildScrollView(
          child: Column(
            children: [
              Padding(
                padding: const EdgeInsets.all(8.0),
                child: Form(
                    child: Column(
                  children: [
                    TextField(
                      controller: accountIdController,
                      decoration: const InputDecoration(
                        border: OutlineInputBorder(),
                        labelText: 'Account ID',
                      ),
                    ),
                    const SizedBox(
                      height: 10,
                    ),
                    TextField(
                      controller: amountController,
                      decoration: const InputDecoration(
                        border: OutlineInputBorder(),
                        labelText: 'Amount',
                      ),
                    ),
                    const SizedBox(
                      height: 10,
                    ),
                    ElevatedButton(
                        onPressed: () {
                          setState(() {
                            final transaction = Transaction(
                              accountId: accountIdController.text,
                              amount: amountController.text,
                              transactionId:
                                  '', // Assuming transactionId is generated by the server
                              createdAt:
                                  '', // Assuming createdAt is generated by the server
                            );
                            futureTransaction = createTransaction(transaction);
                          });
                        },
                        child: const Text('Submit'))
                  ],
                )),
              ),
              FutureBuilder<List<Transaction>>(
                  future: futureTransaction,
                  builder: (context, snapshot) {
                    if (snapshot.hasData) {
                      return ListView.builder(
                          shrinkWrap: true,
                          itemCount: snapshot.data!.length,
                          itemBuilder: (context, index) {
                            final transaction = snapshot.data![index];
                            return Container(
                              margin: const EdgeInsets.all(8.0),
                              padding: const EdgeInsets.all(8.0),
                              decoration: BoxDecoration(
                                border: Border.all(color: Colors.grey),
                                borderRadius: BorderRadius.circular(10),
                              ),
                              child: Column(
                                children: [
                                  Row(
                                    children: [
                                      Text(
                                          'Transferred \$ ${transaction.amount} from '),
                                    ],
                                  ),
                                  Row(
                                    children: [
                                      Text(transaction.accountId),
                                    ],
                                  ),
                                  Row(
                                    children: [
                                      Text(
                                          'The current balance is \$  ${transaction.amount}'),
                                    ],
                                  ),
                                ],
                              ),
                            );
                          });
                    } else if (snapshot.hasError) {
                      print(snapshot.error);
                      return Text('${snapshot.error}');
                    }
                    return const CircularProgressIndicator();
                  })
            ],
          ),
        ));
  }
}
